experiment_name: "imp_baseline"
seed: 42

data:
  batch_size: 64
  num_workers: 0

model:
  pretrained: True
  checkpoint: null # path to load existing model

method: "imp"

training:
  epochs: 5       # phase 1: Initial Training
  lr: 0.001
  device: "cuda"
  save_dir: "output/models"

pruning:
  retrain_epochs: 5   # phase 3: Retraining after pruning
  targets: [0.05, 0.1, 0.15]